<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <AssemblyName>MetaMystia</AssemblyName>
    <Product>MetaMystia</Product>
    <Version>0.26.2</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>MetaMystia</RootNamespace>
    <GamePath>M:\Release4.4.0e</GamePath>
    <OutputPath>$(GamePath)\BepInEx\plugins</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <Target Name="RenameBuildOutput" AfterTargets="Build">
    <PropertyGroup>
      <RenamedAssembly>$(AssemblyName)-v$(Version)</RenamedAssembly>
      <RenamedAssemblyPath>$(OutputPath)$(RenamedAssembly)</RenamedAssemblyPath>
    </PropertyGroup>
    <Move SourceFiles="$(TargetPath)" DestinationFiles="$(RenamedAssemblyPath)$(TargetExt)" />
    <Message Text="Renamed $(TargetPath) to $(RenamedAssemblyPath)$(TargetExt)" Importance="High" />
  </Target>

  <Target Name="CopyToExtraOutputPaths" AfterTargets="Build" DependsOnTargets="RenameBuildOutput">
    <ItemGroup>
      <ExtraOutputPaths Include="D:\Touhou Mystia Izakaya v4.3.0\BepInEx\plugins" />
    </ItemGroup>
    <Copy SourceFiles="$(RenamedAssemblyPath)$(TargetExt)" DestinationFolder="@(ExtraOutputPaths)"
      SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).pdb" DestinationFolder="@(ExtraOutputPaths)"
      SkipUnchangedFiles="true" />
    <Message Text="Copied $(RenamedAssemblyPath)$(TargetExt) to @(ExtraOutputPaths)"
      Importance="High" />
  </Target>

  <Target Name="PatchIl2CppInteropHarmonySupport" AfterTargets="Build">
    <Copy SourceFiles="Patches\Native\Runtime\Il2CppInterop.HarmonySupport.dll"
      DestinationFolder="$(GamePath)\BepInEx\core"
      SkipUnchangedFiles="true" />
    <Message Text="Patched Il2CppInterop.HarmonySupport.dll → $(GamePath)\BepInEx\core"
      Importance="High" />
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="Patches\Native\Runtime\Il2CppInterop.HarmonySupport.dll" />
    <EmbeddedResource Include="Debugger\login.html" />
    <EmbeddedResource Include="Debugger\index.html" />
    <EmbeddedResource Include="ResourceEx\AssetManagement\public.pem" />
    <EmbeddedResource Include="UI\Locales\en.json" />
    <EmbeddedResource Include="UI\Locales\zh-CN.json" />
    <EmbeddedResource Remove="LogGenerator\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="MetaMystia.Generators\MetaMystia.Generators.csproj"
      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="MetaMystia.Generators\**" />
    <EmbeddedResource Remove="MetaMystia.Generators\**" />
    <None Remove="MetaMystia.Generators\**" />
    <Compile Remove="LogGenerator\**" />
    <None Remove="LogGenerator\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MystiaReverse\**" />
    <EmbeddedResource Remove="MystiaReverse\**" />
    <None Remove="MystiaReverse\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MetaMystia.Generators\**" />
    <EmbeddedResource Remove="MetaMystia.Generators\**" />
    <None Remove="MetaMystia.Generators\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DebugImpl\**" />
    <EmbeddedResource Remove="DebugImpl\**" />
    <None Remove="DebugImpl\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="meta-mystia-network\**" />
    <EmbeddedResource Remove="meta-mystia-network\**" />
    <None Remove="meta-mystia-network\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="Costura.Fody" Version="6.*">
      <PrivateAssets>all</PrivateAssets>
      <Private>False</Private>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MemoryPack" Version="1.21.4">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NLua" Version="1.7.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="KeraLua" Version="1.4.9" GeneratePathProperty="true">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>native</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(PkgKeraLua)\runtimes\win-x64\native\lua54.dll">
      <Link>costura-win-x64\lua54.dll</Link>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GamePath)\BepInEx\interop\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(GamePath)\BepInEx\interop\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>$(GamePath)\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx.Preloader.Core">
      <HintPath>$(GamePath)\BepInEx\core\BepInEx.Preloader.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.Common">
      <HintPath>$(GamePath)\BepInEx\core\BepInEx.Unity.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(GamePath)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(GamePath)\BepInEx\interop\Il2CppSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(GamePath)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>$(GamePath)\BepInEx\interop\Il2CppSystem.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Net.Http">
      <HintPath>$(GamePath)\BepInEx\interop\Il2CppSystem.Net.Http.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>$(GamePath)\BepInEx\interop\UniTask.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.TilemapModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.GridModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.DirectorModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.InputModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GamePath)\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(GamePath)\BepInEx\interop\Unity.Addressables.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GamePath)\BepInEx\interop\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.InputSystem.dll">
      <HintPath>$(GamePath)\BepInEx\interop\Unity.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>$(GamePath)\BepInEx\interop\Unity.ResourceManager.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DEYU.Singletons">
      <HintPath>$(GamePath)\BepInEx\interop\DEYU.Singletons.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DEYU.AssetHandleUtility">
      <HintPath>$(GamePath)\BepInEx\interop\DEYU.AssetHandleUtility.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DEYU.AdpUISystemUniTaskExtension">
      <HintPath>$(GamePath)\BepInEx\interop\DEYU.AdpUISystemUniTaskExtension.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Omt.GamePlatformAPI">
      <HintPath>$(GamePath)\BepInEx\interop\Omt.GamePlatformAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Omt.GamePlatformAPI">
      <HintPath>$(GamePath)\BepInEx\interop\DEYU.AdaptiveUISystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MemoryPack.Core">
      <HintPath>$(NuGetPackageRoot)memorypack\1.21.4\lib\netstandard2.0\MemoryPack.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GamePath)\BepInEx\interop\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
